import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    <div  className={styles.body}>
        <div>
            <h1>Rock Paper Scissors</h1>
    
            <h2>score: <span id="score">0</span> </h2>
        </div>

        
    

        <div  className={styles.grid}>
            <div className={styles.items}>
                <div className={styles.play_imgs}  ><Image width={130} height={130} src="/imgs/paper.png" alt="paper img" /></div>
                <div className={styles.play_imgs}  style={{animationDelay:".5s"}}><Image width={130} height={130} src="/imgs/rock.png" alt="rock img" /></div>
                <div className={styles.play_imgs}  style={{animationDelay:".7s"}}><Image width={130} height={130} src="/imgs/scissors.png" alt="scissors img" /></div>
            </div>

        </div>


    </div>
      


    </div>
  )
}
